services:
  - type: web
    name: acousticedge
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /api/inspect/health
    envVars:
      - key: INFERENCE_URL
        value: http://127.0.0.1:8000
