services:
  - type: web
    name: acousticedge
    env: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    healthCheckPath: /api/inspect/health